# Generated by Django 5.0.3 on 2024-04-16 20:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_session_endtime_alter_session_starttime'),
    ]

    operations = [
        migrations.RenameField(
            model_name='goal',
            old_name='no_of_sessions',
            new_name='no_of_minutes',
        ),
        migrations.RemoveField(
            model_name='goal',
            name='deadline',
        ),
        migrations.RemoveField(
            model_name='goal',
            name='progress',
        ),
    ]
