# Generated by Django 5.0.3 on 2024-04-16 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_rename_no_of_sessions_goal_no_of_minutes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='goal',
            name='completed_minutes',
            field=models.IntegerField(default=0),
        ),
    ]
