# Generated by Django 5.0.3 on 2024-04-16 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_goal_completed_minutes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goal',
            name='completed_minutes',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
