# Generated by Django 5.0.3 on 2024-04-14 23:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_remove_task_priority'),
    ]

    operations = [

    ]
