# Generated by Django 5.0.3 on 2024-04-15 00:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_remove_task_priority_alter_task_task_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='priority',
        ),
    ]
